# Numpy

In [1]:
import numpy as dsa

In [2]:
dsa.__version__

'1.21.5'

In [ ]:
# !pip install numpy==1.22.2    #instruçao para instalar uma versao exata do pacote em Py

## Criando arrays numpy

In [4]:
arr1 = dsa.array([10, 21, 32, 43, 48, 15, 76, 57, 89])  #array a parti de lst py

In [5]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [7]:
type(arr1)   # um objeto do tipo ndarray é um recipiente multidimensional de itens do mesmo tipo e tamanho

numpy.ndarray

In [8]:
arr1.shape

(9,)

## Indexaçao em arrays 

In [9]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [10]:
arr1[4]

48

In [11]:
arr1[1:4]   # retorna todos entre o 1 e 4 (excluindo o 4)

array([21, 32, 43])

In [13]:
arr1[1:4+1]

array([21, 32, 43, 48])

In [14]:
indices = [1, 2, 5, 6]     #cria uma lista de indices

In [15]:
arr1[indices]    # imprimindo os elementos dos indices

array([21, 32, 15, 76])

In [18]:
mask = (arr1 % 2 == 0)  # cri uma máscara == padrão booleana para os elementos pares 

In [19]:
mask

array([ True, False,  True, False,  True, False,  True, False, False])

In [20]:
arr1[mask]

array([10, 32, 48, 76])

In [21]:
arr1[0] = 100    # alterando um elemento array 

In [22]:
print(arr1)

[100  21  32  43  48  15  76  57  89]


In [23]:
try:                                    # n é possivel incluir elemento de outro tipo
    arr1[0] = 'Novo elemento'
except:
    print("Operaçao n permitida")

Operaçao n permitida


In [24]:
 arr1[0] = 'Novo elemento'

ValueError: invalid literal for int() with base 10: 'Novo elemento'

## Funçoes Numpy

In [25]:
arr2 = dsa.array([1, 2, 3, 4, 5])

In [26]:
print(arr2)

[1 2 3 4 5]


In [27]:
type(arr2)

numpy.ndarray

In [29]:
arr2   # digite . tab para métodos

array([1, 2, 3, 4, 5])

In [30]:
arr2.cumsum()   # soma acumulada dos elementos

array([ 1,  3,  6, 10, 15], dtype=int32)

In [31]:
arr2.cumprod()    # soma acumulada dos produtos

array([  1,   2,   6,  24, 120], dtype=int32)

In [33]:
dsa                # para visualizar funces e manipular obj numpy

<module 'numpy' from 'C:\\Users\\Administrator\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [35]:
arr3 = dsa.arange(0, 50, 5)    # cria progressâo aritmetica a partir de um intervalo - start, stop, step

In [36]:
print(arr3)

[ 0  5 10 15 20 25 30 35 40 45]


In [37]:
type(arr3)

numpy.ndarray

In [38]:
dsa.shape(arr3)

(10,)

In [39]:
print(arr3.dtype)

int32


In [40]:
arr4 = dsa.zeros(10)   # cria um array preenchido com zeros

In [41]:
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [42]:
arr5 = dsa.eye(3)    # retorna 1 nas posiçoes em diagonal e 0 no restante

In [43]:
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
arr6 = dsa.diag(dsa.array([1, 2, 3, 4])) # valores passados coo parametro formam uma diagnoal

In [45]:
print(arr6)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [46]:
arr7 = dsa.array([True, False, False, True])  #array de valores booleanos

In [47]:
print(arr7)

[ True False False  True]


In [48]:
arr8 = dsa.array(["Linguagem Python", "Linguagem R", "Linguagem JU"])  # array de strings

In [49]:
print(arr8)

['Linguagem Python' 'Linguagem R' 'Linguagem JU']


In [50]:
print(dsa.linspace(0, 10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [51]:
print(dsa.linspace(0, 10, 15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [52]:
print(dsa.logspace(0, 10))

[1.00000000e+00 1.59985872e+00 2.55954792e+00 4.09491506e+00
 6.55128557e+00 1.04811313e+01 1.67683294e+01 2.68269580e+01
 4.29193426e+01 6.86648845e+01 1.09854114e+02 1.75751062e+02
 2.81176870e+02 4.49843267e+02 7.19685673e+02 1.15139540e+03
 1.84206997e+03 2.94705170e+03 4.71486636e+03 7.54312006e+03
 1.20679264e+04 1.93069773e+04 3.08884360e+04 4.94171336e+04
 7.90604321e+04 1.26485522e+05 2.02358965e+05 3.23745754e+05
 5.17947468e+05 8.28642773e+05 1.32571137e+06 2.12095089e+06
 3.39322177e+06 5.42867544e+06 8.68511374e+06 1.38949549e+07
 2.22299648e+07 3.55648031e+07 5.68986603e+07 9.10298178e+07
 1.45634848e+08 2.32995181e+08 3.72759372e+08 5.96362332e+08
 9.54095476e+08 1.52641797e+09 2.44205309e+09 3.90693994e+09
 6.25055193e+09 1.00000000e+10]


In [53]:
print(dsa.logspace(0, 5, 10))

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]
