## Operaçoes matematicas com arrays numpy

In [1]:
import numpy as dsa

In [2]:
arr15 = dsa.arange(1, 10)

In [3]:
print(arr15)

[1 2 3 4 5 6 7 8 9]


In [4]:
dsa.sum(arr15)

45

In [5]:
dsa.prod(arr15)  # retorna o produto dos elementos 

362880

In [6]:
dsa.cumsum(arr15)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [7]:
arr16 = dsa.array([3, 2, 1])
arr17 = dsa.array([1, 2, 3])

In [8]:
arr18 = dsa.add(arr16, arr17)   # soma dos arrays

In [9]:
print(arr18)

[4 4 4]


In [10]:
arr19 = dsa.array([[1, 2], [3, 4]])
arr20 = dsa.array([[5, 6], [0, 7]])

In [11]:
arr19.shape

(2, 2)

In [12]:
arr20.shape

(2, 2)

In [13]:
print(arr19)

[[1 2]
 [3 4]]


In [15]:
arr21 = dsa.dot(arr19, arr20)   #multiplicar as duas matrizes

In [16]:
print(arr21)

[[ 5 20]
 [15 46]]


In [17]:
arr21 = arr19 @ arr20  #op a func dot

In [18]:
print(arr21)

[[ 5 20]
 [15 46]]


In [19]:
arr21 = dsa.tensordot(arr19, arr20, axes = ((1), (0)))

In [20]:
print(arr21)

[[ 5 20]
 [15 46]]


## Slicing de arrays numPy

In [21]:
arr22 = dsa.diag(dsa.arange(3)) #cria um array

In [23]:
print(arr22)

[[0 0 0]
 [0 1 0]
 [0 0 2]]


In [24]:
arr22[1,1]

1

In [26]:
arr22[2, 2]

2

In [27]:
arr22[1]

array([0, 1, 0])

In [28]:
arr22[:, 2]

array([0, 0, 2])

In [29]:
arr23 = dsa.arange(10)

In [30]:
print(arr23)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
arr23[2:9:3]  # start:end:step  -- tudo entre 2 e 9, saltando de 3 em 3

array([2, 5, 8])

In [32]:
a = dsa.array([1, 2, 3, 4])
b = dsa.array([4, 2, 2, 4])

In [33]:
a == b   # comparaçcao item a item

array([False,  True, False,  True])

In [34]:
dsa.array_equal(arr22, arr23)

False

In [35]:
arr23.min()

0

In [36]:
arr23.max()

9

In [37]:
dsa.array([1, 2, 3]) + 1.5  # somando um valor a cada array

array([2.5, 3.5, 4.5])

In [38]:
arr24 = dsa.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])

In [39]:
arr25 = dsa.around(arr24)   #método around para arredondar

In [40]:
print(arr25)

[1. 2. 2. 2. 4. 4.]


In [42]:
arr26 = dsa.array([[1,2,3,4], [5,6,7,8]])

In [43]:
print(arr26)

[[1 2 3 4]
 [5 6 7 8]]


In [44]:
arr27 = arr26.flatten()  # achatando a matriz

In [45]:
print(arr27)

[1 2 3 4 5 6 7 8]


In [46]:
arr28 = dsa.array([1, 2, 3])

In [47]:
print(arr28)

[1 2 3]


In [48]:
dsa.repeat(arr28, 3)  # repetindo os elementos de um array

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [50]:
dsa.tile(arr28,3)  # repetindo os elements de um array

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [51]:
arr29 = dsa.array([5, 6])

In [53]:
arr30 = dsa.copy(arr29)

In [54]:
print(arr30)

[5 6]
